package errors

const (
	USER_NOT_FOUND                                      = 1   // User was not found.
	GAME_NOT_FOUND                                      = 2   // Game was not found
	WITHDRAW_AMOUNT_NEGATIVE                            = 3   // Withdrawal amount specified was negative.
	DEPOSIT_AMOUNT_NEGATIVE                             = 6   // Deposit amount specified was negative
	INSUFFICIENT_FUNDS                                  = 7   // User does not have enough funds.
	WALLET_TRANSACTION_DESCRIPTION_REQUIRED             = 8   // A wallet transaction requires a description
	UNKNOWN_ERROR                                       = 9   // Unexpected error occurred.
	CURRENCY_NOT_SUPPORTED                              = 10  // The supplied currency code was not found, or is not supported.
	SERVICE_AUTHENTICATION_ERROR                        = 11  // Service Authentication Failed
	PLAYER_LIMIT_EXCEEDED                               = 12  // Play Limit has been reached.
	NO_GAMES_FOUND_FOR_FILTER                           = 13  // No games found for the specified filters
	INVALID_GAME_CATEGORY                               = 14  // Invalid or no Game Category Specified.
	INVALID_TRANSACTION_TYPE                            = 15  // Invalid transaction type specified
	ACCOUNT_BLOCKED                                     = 17  // Your account has been blocked.
	KYC_SEND_DOCUMENTS                                  = 19  // Please send KYC documents by email.
	INVALID_AUTHENTICATION_TOKEN                        = 20  // You have supplied an invalid Authentication Token.
	UNAUTHORIZED_AUTHENTICATION_TOKEN                   = 21  // The authentication token passed is not authorized
	MISSING_AUTHENTICATION_TOKEN                        = 22  // No authentication token was found with the request
	ACCOUNT_COOLDOWN                                    = 23  // Your account has been locked for some minutes because there are too many failed attempts
	EMAIL_NOT_VERIFIED                                  = 24  // Your email was not verified.
	GAME_SESSION_INVALID                                = 25  // An invalid game session was supplied
	GAME_SESSION_EXPIRED                                = 26  // The game session supplied is expired.
	USER_IS_SELF_EXCLUDED                               = 27  // The user is selfexcluded.
	TNC_ACCEPTANCE_REQUIRED                             = 28  // The user is required to accept Terms & Conditions
	USER_IP_RESTRICTED                                  = 29  // The user's IP address is restricted.
	USER_NEEDS_COOLING_OFF                              = 30  // Self-exclusion is over and the user must contact the operator to lift the exclusion.
	USER_IN_COOLING_OFF                                 = 31  // Self-exclusion is over but the user is in the cooling period.
	DAILY_PROTECTION_EXCEEDED                           = 32  // The user exceeded their daily protection limit.
	WEEKLY_PROTECTION_EXCEEDED                          = 35  // The user exceeded their weekly protection limit.
	MONTHLY_PROTECTION_EXCEEDED                         = 37  // The user exceeded their monthly protection limit.
	GAMEPLAY_DURATION_EXCEEDED                          = 38  // The user exceeded their game play duration.
	LOSS_LIMIT_EXCEEDED                                 = 39  // The user exceeded their loss limit
	USER_BLOCKED_FROM_GAME                              = 40  // The user is not permitted to play this game.
	USERNAME_ALREADY_EXISTS                             = 41  // This username already exists.
	EMAIL_ALREADY_EXISTS                                = 42  // This email already exists.
	CANNOT_DELEGATE_DELEGATED                           = 43  // You cannot delegate and already delegated token
	INTERNAL_SERVER_ERROR                               = 44  // An Internal Server error has occurred! Please check your request and try again. If you think your request is correct,  please contact the person in charge.
	INVALID_VERIFICATION_CODE                           = 45  // The Verification Code you have entered is invalid or has already been used.
	TRANSACTION_ALREADY_PROCESSED_DIFF                  = 46  // The transaction has already been processed, with different details.
	TRANSACTION_ALREADY_PROCESSED                       = 47  // The transaction has already been processed.
	INVALID_PASSWORD                                    = 48  // You have supplied an invalid Password
	INVALID_SECURITY_ANSWER                             = 49  // The Security Answer you have supplied is Invalid.
	EMAIL_NOT_FOUND                                     = 50  // No user was found for the supplied email address
	INVALID_PASSWORD_RECOVERY_CODE                      = 51  // The Password Recovery Code you have supplied is invalid.
	USER_LOGGED_OUT                                     = 52  // The session token used has been logged out.
	CHALLENGE_INVALID                                   = 54  // Your challenge is invalid. This means that either it has been already used or it has timed out.
	DATE_RANGE_TOO_BIG                                  = 55  // The date range requested is too big (Maximum is 62 days).
	SYSTEM_WALLET_NOT_INITIALISED                       = 56  // The system wallet has not been initialised correctly.
	PARAMETER_NOT_SUPPLIED                              = 57  // A required parameter was not supplied
	WAGER_NOT_FOUND                                     = 58  // The casino wager was not found.
	USER_EXCEEDED_LIMITS                                = 59  // The user exceeded his/her limit
	GAME_ACTIVITY_NOT_FOUND                             = 60  // The game activity was not found.
	OPERATION_NOT_ALLOWED                               = 61  // The operation is not allowed.
	USER_SELF_EXCLUDED                                  = 62  // User has self-excluded himself and is not allowed to login
	USERNAME_TOO_LONG                                   = 65  // The username you have entered exceeds 17 characters.
	RESPONSIBLE_GAMING_LIMIT_EXCEEDED                   = 66  // The user exceeded his/her limit
	REQUEST_DATA_INVALID                                = 98  // Request data is missing entirely or has critical parts missing
	MOBILE_PREFIX_NULL_OR_EMPTY                         = 99  // Mobile prefix is null or empty.
	MOBILE_NULL_OR_EMPTY                                = 100 // Mobile is null or empty.
	MOBILE_OR_PREFIX_INVALID                            = 101 // Mobile and prefix combination is invalid
	MOBILE_MOBILE_VERIFICATION_CODE_COMBINATION_INVALID = 102 // Mobile & mobile verification code combination is invalid.
	MOBILE_VERIFICATION_CODE_NULL_OR_EMPTY              = 103 // Mobile verification code is null or empty.
	SMS_PROVIDER_ERROR                                  = 104 // Something went wrong with the SMS provider
	SMS_NOT_DELIVERED                                   = 105 // SMS not delivered to recipient.
	X_FORWARDED_FOR_NOT_VALID_IPv4                      = 106 // X-Forwarded-For did not contain a valid IPv4 IP.
	VERIFICATION_TYPE_ID_NOT_VALID_FOR_IP               = 107 // Verification Type is not valid for IP.
	VALIDATION_ERROR                                    = 108 // Validation Error.
	LAST_SMS_NOT_DELIVERED                              = 109 // Last SMS was not delivered to recipient
	PHONE_OR_PREFIX_INVALID                             = 110 // Phone and phone code combination is invalid.
	EMAIL_IS_INVALID                                    = 111 // Email is not a valid email.
	USERNAME_IS_INVALID                                 = 112 // Username is not a valid username.
	ERROR_NOT_DEFINED                                   = 113 // Error has not yet been defined.
	MOBILE_AND_PREFIX_COMBINATION_ALREADY_REGISTERED    = 114 // Mobile and prefix combination is already registered with us.
	PHONE_AND_PREFIX_COMBINATION_ALREADY_REGISTERED     = 115 // Phone and phone code combination is already registered with us
	MOBILE_AND_PREFIX_INVALID                           = 116 // Mobile and prefix combination is invalid.
	PHONE_AND_PREFIX_INVALID                            = 117 // Phone and phone prefix combination is invalid.
	MOBILE_AND_PREFIX_NOT_TRUSTWORTHY                   = 118 // Mobile and prefix combination has been deemed untrustworthy.
	PHONE_AND_PREFIX_NOT_TRUSTWORTHY                    = 119 // Phone and phone prefix combination has been deemed untrustworthy.
	GAME_RESTRICTED                                     = 120 // The game is restricted
	TERMS_NOT_ACCEPTED                                  = 121 // The user did not accept the terms and conditions
	USER_IS_NOT_OF_LEGAL_AGE                            = 122 // User is not of legal age.
	SESSION_SELF_EXCLUSION                              = 123 // Player is not allowed to have a session because of a session selfexclusion.
	INCORRECT_ODDS                                      = 124 // Incorrect odds have been entered
	MARKET_IS_CLOSED                                    = 125 // The market is closed
	INPUT_IS_INCORRECT                                  = 126 // The players input is not valid
	ODDS_HAVE_CHANGED                                   = 127 // The odds are no longer valid as have changed
	NOT_ENOUGH_MONEY_TO_WAGER_BET                       = 128 // The player does not have sufficient funds to place bet
	STAKE_TOO_HIGH                                      = 129 // The stake is above permitted value
	USER_PASSWORD_INCORRECT                             = 130 // Player entered incorrect password
	FPP_LESS_THAN_ZERO                                  = 131 // The FPP is less than 0
	ACCOUNT_ALREADY_VERIFIED                            = 132 // The player’s account has already been verified.
	LANGUAGE_IS_INVALID                                 = 133 // The language is not valid
	ACCOUNT_NOT_VERIFIED                                = 134 // The player’s account has not been verified
	MISSING_USER_AGENT                                  = 135 // User Agent is missing
	INPUT_ILLEGAL                                       = 136 // The input is not valid
	POKER_PROVIDER_NOT_CONFIGURED                       = 137 // The poker provider has not been set up
	POKER_PROVIDER_IS_NOT_CONFIGURED_CORRECTLY          = 138 // The poker provider has not been correctly configured
	POKER_PROVIDER_IS_OF_WRONG_TYPE                     = 139 // The provider is not of the correct type
	SESSION_STAKE_PROTECTION_EXCEEDED                   = 140 // The value of the session stake protection has exceed the permitted amount
	MAX_STAKE_PROTECTION_EXCEEDED                       = 141 // The maximum stake protection has been exceeded
	GAME_IS_OFFLINE                                     = 142 // The selected game is offline
	DEMO_PLAY_NOT_SUPPORTED                             = 143 // Demo play is not supported for this game
	SMS_HTTP_REQUEST_FAILED                             = 144 // Protocol request failure
	SMS_TIMEOUT_HAS_NOT_EXPIRED                         = 145 // Sms timeout has not yet expired
	SMS_STATUS_CHECK_FAILED                             = 146 // The SMS status check failed
	SMS_STATUS_CHECK_NO_REFID                           = 147 // The SMS status check had no Ref ID
	MAXIMUM_BONUS_BET                                   = 148 // The value reached max allowed for the bonus bet
	INVALID_PROMO_VALIDITY                              = 149 // The promotion was no longer valid
	INVALID_BONUS_ID                                    = 150 // The bonus is was not valid
	PENDING_PROMO_CODE                                  = 151 // The promo code is pending
	INVALID_USER_BONUS_ID                               = 152 // The user bonus id is not valid
	INVALID_PROMO_CODE_STATUS                           = 153 // The promo code status is not valid
	WAGER_LIMIT_EXCEEDED                                = 154 // The bet limit has been exceeded
	UNSUPPORTED_EMAIL_TEMPLATE_ID                       = 155 // The template id is not supported
	RESERVED_KEY_EMAIL_TEMPLATE_PLACEHOLDER_VALUES      = 156 // The values supplied are reserved
	SMS_OPERATION_TYPE_INVALID                          = 157 // The sms operation was invalid
	GAMEVARIANT_NOT_FOUND                               = 158 // The game variant was not found
	MIN_ODDS                                            = 159 // The min odds has not been reached
	NO_GAMES_SELECTED                                   = 160 // No games were selected
	STAKE_TOO_LOW                                       = 161 // The value of the bet was too low
	MISSING_BONUSCODE                                   = 162 // A bonus code was missing
	INVALID_BONUSCODE                                   = 163 // The bonus code was not valid
	BONUS_NOT_VISIBLE                                   = 164 // The bonus is not visible
	INVALID_IBAN_CHECKSUM                               = 165 // The IBAN checksum is not valid
	COUNTRY_INVALID                                     = 166 // The country code is not valid
	NO_BONUSES                                          = 167 // No bonuses were found
	INVALID_SECURITY_QUESTION                           = 169 // The security question is not valid
	MAX_COUPON_MATCHES                                  = 170 // The maximum coupon matches has been reached
	VENDOR_NOT_FOUND                                    = 171 // The vendor was not found
	VENDOR_NO_TOURNAMENTS                               = 172 // No tournaments were found for the specified vendor
	TOURNAMENT_NOT_FOUND                                = 173 // The tournament could not be found
	SMS_SERVICE_NOT_ENABLED                             = 174 // The SMS service has not been enabled
	GAME_ROUND_ENDED                                    = 175 // The game round has ended
	GAMES_ROUND_BET_NOTFOUND                            = 176 // The bet for the games round was not found
	GAMES_ROUND_RESULT_NOTFOUND                         = 177 // The result for the games round was not found
	INVALID_REFERENCE                                   = 178 // The reference provided was not valid
	GAME_ROUND_NOT_FOUND                                = 179 // The Game round was not found
	INCORRECT_TOTAL                                     = 180 // The total was not correct
	MISSING_OPERATOR_TOKEN                              = 181 // The required operator token is missing
	ACCOUNT_BLOCKED_MAX_LOGIN_ATTEMPTS_EXCEEDED         = 182 // The account has now been blocked due to exceeding max number of login attempts
	RESTRICTION_OBJECT_NULL                             = 183
	RESTRICTION_PREVIOUS_BONUS_REQUIRED                 = 184 // A previous bonus is required before this one can be awarded.
	RESTRICTION_EXPIRED                                 = 185 // The restriction has now expired.
	RESTRICTION_INVALID_INPUT                           = 186 // The data entered is not valid.
	RESTRICTION_USER                                    = 187 // The user is restricted.
	RESTRICTION_ROLE                                    = 188 // The role does not have permission to perform this.
	RESTRICTION_COUNTRY                                 = 189 // The country is restricted
	RESTRICTION_PAYMENT_COUNTRY                         = 190 // The country of payment is restricted.
	RESTRICTION_AFFILIATE                               = 191 // The affiliate is restricted/
	RESTRICTION_VENDOR                                  = 192 // The vendor is restricted/
	RESTRICTION_ADMIN_CATEGORY                          = 193 // The admin category is restricted.
	RESTRICTION_GAME                                    = 194 // The game is restricted
	RESTRICTION_DEVICE                                  = 195 // There is a restriction on the device type.
	BONUS_MISSING_INPUT_DETAILS                         = 196 // The supplied details were incomplete.
	BONUS_WELCOME_ONGOING                               = 197 // The welcome bonus is ongoing
	BONUS_RESTRICTED_MISSING                            = 198 // The bonus restriction is missing
	BONUS_RESTRICTED                                    = 199 // This bonus is restricted
	BONUS_MISSING_DETAILS                               = 200 // The supplied details were incomplete
	BONUS_INVALID_CLAIM_PERIOD                          = 201 // The claim period for  the bonus is not valid
	BONUS_NOT_FIRST_DEPOSIT                             = 202 // This is not the first deposit
	BONUS_MISSING_CODE                                  = 203 // The Bonus code was missing
	BONUS_INVALID_CODE                                  = 204 // An invalid bonus code was entered
	BONUS_CLAIM_EARLY                                   = 205 // The bonus claim was early
	BONUS_CLAIM_LATE                                    = 206 // The bonus claim was late
	BONUS_NO_GAMES_SELECTED                             = 207 // No games were selected for the bonus
	BONUS_INVALID_GAME_TRIGGER                          = 208 // The game trigger was not valid
	BONUS_RELOAD_ONGOING                                = 209 // The reload is ongoing
	BONUS_INVALID_DEPOSIT_COUNT                         = 210 // The number of deposits is not valid for the bonus
	BONUS_MISSING_REDEMPTIONTYPE                        = 211 // The redemption type is missing for this bonus
	BONUS_NODEPOSIT_ONGOING                             = 212 // The ‘no deposit’ bonus is ongoing
	BONUS_INVALID_USER                                  = 213 // The bonus is not valid for the specified user
	BONUS_INVALID_REGDATE                               = 214 // The registration date is not valid for this bonus
	BONUS_INVALID_CAMPAIGNFUNDS                         = 215 // The bonus campaign fund is invalid
	BONUS_CAMPAIGNFUNDS_INSUFFICIENT                    = 216 // Insufficient bonus campaign funds are available
	BONUS_ALREADY_ONGOING                               = 217 // This bonus is already ongoing
	BONUS_USER_NOT_IN_LIST                              = 218 // The player is not legible for the bonus
	BONUS_MONEY_EXCEEDED                                = 219 // The amount of bonus money has been exceeded
	BONUS_CREATE_FAILED                                 = 220 // The bonus was not created
	BONUS_DEPOSIT_MISSING                               = 221 // The required deposit was missing
	BONUS_DEPOSIT_INSUFFICIENT                          = 222 // The deposit was not sufficient for the bonus to be awarded
	BONUS_CLAIMED                                       = 223 // The bonus was claimed
	BONUS_CASHBACK_NULL                                 = 224 // The bonus cashback value was null
	BONUS_CASHBACK_MISSING_PAYOUT                       = 225 // There is a missing payout for the cashback
	BONUS_CASHBACK_MISSING_DATES_CUSTOM                 = 226 // The custom dates for the cashback bonus are missing
	BONUS_CASHBACK_CLAIMED_CUSTOM                       = 227 // The cashback has been claimed for the custom bonus.
	BONUS_CASHBACK_INVALID_PERIOD_DAILY                 = 228 // The bonus cashback period entered is invalid
	BONUS_CASHBACK_CLAIMED_DAILY                        = 229 // The daily cashback has been claimed
	BONUS_CASHBACK_SCHEDULER_DATE_MISSING               = 230 // The date is missing from the scheduler
	BONUS_CASHBACK_INVALID_PERIOD_WEEKLY                = 231 // The specified period is not valid
	BONUS_CASHBACK_CLAIMED_WEEKLY                       = 232 // The weekly cashback has been claimed
	BONUS_CASHBACK_INVALID_PERIOD_MONTHLY               = 233 // The specified cashback period is not valid
	BONUS_CASHBACK_CLAIMED_MONTHLY                      = 234 // The monthly cashback has been claimed
	BONUS_CASHBACK_DATE_NULL                            = 235 // The date was empty
	BONUS_CASHBACK_NOT_SUPPORTED                        = 236 // Cashback is not supported
	BONUS_CASHBACK_INVALID_PERCENTAGE                   = 237 // The specified % is not valid
	BONUS_CASHBACK_BONUSMONEY_ZERO                      = 238 // The bonus money is zero
	BONUS_CASHBACK_USERLOSSES_NULL                      = 239 // User losses is null
	BONUS_SPORTSWELCOME_ONGOING                         = 240 // The sports welcome bonus is ongoing
	BONUS_SPORTSRELOAD_ONGOING                          = 241 // The sports reload bonus is ongoing
	BONUS_SPORTSNODEPOSIT_ONGOING                       = 242 // The sports no deposit bonus is ongoing
	BONUS_INSUFFICIENT_FUNDS                            = 243 // There are insufficient funds
	BONUS_USER_NOT_FOUND                                = 244 // The specified user was not found
	BONUS_REGISTERED_PRIOR_DATE                         = 245 // The player registration date was prior to the date permitted for the bonus
	RESTRICTION_SPORTS_SECTION                          = 246 // The section is restricted
	RESTRICTION_PREVIOUS_BONUS_CLAIM                    = 247 // The bonus has been claimed before
	GENERIC                                             = 248
	OUTRIGHT_MARKET_IS_DISABLED                         = 249 // The outright market is disabled
	NO_ODDS_IN_BET                                      = 250 // No odds were found in the bet
	INVALID_MARKET                                      = 251 // The market is not valid
	INVALID_ODDS                                        = 252 // The specified odds are invalid
	USER_COUNTRY_FORBIDDEN                              = 253 // The player’s country is not permitted to bet
	BET_MARKET_MORE_THAN_ONCE                           = 254 // The player has bet on this market already
	ODDS_SAME_MATCH_IN_COMBO                            = 255
	SAME_TEAM_COMBO                                     = 256 // The same team has been named in the combo bet
	xSAME_SPORT_COUNTRY                                 = 256 // The same country has named
	INVALID_AGE                                         = 258 // The player’s age is not valid
	USER_ALREADY_AFFILIATED                             = 259 // The player has already been referred through another affiliate
	INVALID_AFFILIATE_REFERENCE                         = 260 // The affiliate’s reference is not valid
	BONUS_SYSTEM_ERROR                                  = 261 // A system error has occurred
	BONUS_WELCOME_CALC_ERROR                            = 262 // Calculation error on the welcome bonus
	BONUS_IS_ZERO                                       = 263 // The bonus is 0
	BONUS_RELOAD_CALC_ERROR                             = 264 // There is an error in the calculation
	BONUS_FS_VENDOR_LOAD_FAILED                         = 265 // The load of the free spin vendors failed
	BONUS_FS_SPIN_UPDATE_FAILED                         = 266 // The free spin update failed
	BONUS_SPORTS_WELCOME_CALC_ERROR                     = 267 // There is an error in the calculation of the sports welcome bonus
	BONUS_SPORTS_RELOAD_CALC_ERROR                      = 268 // There is an error in the calculation
	TAG_INVALID                                         = 269 // The specified tag is not valid
	OVERRIDE_INVALID_BONUSID                            = 270 // The bonus id is invalid
	OVERRIDE_INVALID_OVERRIDEVALUE                      = 271 // The override value is not valid
	OVERRIDE_BONUS_NOT_SUPPORTED                        = 272 // The bonus is not supported
	OVERRIDE_INVALID_USERID                             = 273 // The userid is not valid
	OVERRIDE_INVALID_SPIN_VALUE                         = 274 // The specified spin value is not valid
	OVERRIDE_BONUSTYPE_NOT_SUPPORTED                    = 275 // The bonus type is not supported
	OVERRIDE_BONUS_MAX_PLAYER_CLAIM                     = 276 // The maximum number of players have claimed bonus
	OVERRIDE_BONUS_PENDING_CLAIMS                       = 277 // The bonus still has pending claims
	OVERRIDE_SYSTEM_ERROR                               = 278 // There was a system error
	OVERRIDE_CLAIM_FAILED                               = 279 // The claim has failed
	OVERRIDE_CANCEL_NO_UPDATES                          = 280 // No updates has been cancelled
	OVERRIDE_EXPIRED_NO_UPDATES                         = 281 // No updates has expired
	OVERRIDE_INVALIDATE_FAILED                          = 282 // The request to invalidate has failed
	TAG_USER_ASSIGNMENT_FAILED                          = 283 // The tag was not assigned
	INVALID_OPERATOR_TOKEN                              = 284 // The supplied operator token was not valid
	USER_LIMIT_INVALID                                  = 285 // The limit was not valid
	BONUS_NO_BONUS                                      = 286 // No Bonuses were found
	MAX_SMS_VERIFICATIONCODE_GUESS_ATTEMPT_EXCEEDED     = 287 // The number of allowed attempts for entering the verification code has been exceeded.
	INVALID_EVENT                                       = 288 // The event is not valid
	NO_EXTERNAL_FREESPIN_PROGRAM_FOUND                  = 289 // The free spin program was not found
	SELFEXCLUSION_CATEGORY_ID_OUT_OF_RANGE              = 290 // The self-exclusion category id was not in the range permitted
	TIMEOUT_CATEGORY_ID_OUT_OF_RANGE                    = 291 // The timeout category id was not in the permitted range.
	BONUS_RFB_CANNOT_CANCEL                             = 292 // The Risk Free bet cannot be cancelled
	BONUS_NO_RISKFREEBETS                               = 293 // No risk free bets were found
	USERNAME_REQUIRED                                   = 294 // The username was not entered
	PASSWORD_REQUIRED                                   = 295 // The password was not entered
	EMAIL_REQUIRED                                      = 296 // The email address was not entered
	FIRST_NAME_REQUIRED                                 = 297 // The first name was not entered
	LAST_NAME_REQUIRED                                  = 298 // The last name was not entered
	ADDRESS1_REQUIRED                                   = 299 // The first line of the address was not entered
	POSTAL_CODE_REQUIRED                                = 300 // The post code was not entered
	CITY_REQUIRED                                       = 301 // The city was not entered
	LANGUAGE_ID_REQUIRED                                = 302 // The language id was not entered
	MOBILE_PREFIX_REQUIRED                              = 303 // The mobile prefix was not entered
	MOBILE_NUMBER_REQUIRED                              = 304 // The mobile number was not entered
	SPENDING_LIMIT_REQUIRED                             = 305 // The spending limit was not entered
	DANISH_CIVIL_REGISTRATION_NUMBER_REQUIRED           = 306 // The Danish Civil Registration number was not entered
	MOBILE_PREFIX_INVALID                               = 307 // An invalid mobile prefix was entered
	MOBILE_INVALID                                      = 308 // The supplied mobile number was not valid
	SPENDING_LIMIT_INVALID                              = 309 // The spending limit is not valid
	SPENDING_LIMIT_INVALID_2                            = 310 // The spending limit is not valid
	PHONE_PREFIX_INVALID                                = 311 // The landline prefix is not valid
	PHONE_INVALID                                       = 312 // The landline number is not valid
	DANISH_CIVIL_REGISTRATION_NUMBER_EXISTS             = 313 // The specified civil registration number already exists
	COUNTRY_NOT_SUPPORTED_BY_REGISTRATION_METHOD        = 314 // The registration method is not supported in the specified country
	MESSAGE_SEND_FAILURE                                = 315 // The message sending failed
	SECURITY_ANSWER_TOO_LONG                            = 316 // The supplied answer exceeded the max allowed length
	DUPLICATE_SECURITY_QUESTIONS                        = 317 // The security questions are the same
	SECURITY_QUESTION_ANSWER_COUNT_MISMATCH             = 318 // The number of questions did not match the number of answers
	SECURITY_QUESTIONS_NOT_ENABLED                      = 319 // The security questions have not been enabled
	SECURITY_QUESTIONS_MISSING                          = 320 // The security questions are missing
	PASSWORD_IS_INVALID                                 = 321 // The password is invalid
	ADDRESS1_INVALID                                    = 322 // Line one of the address is not valid
	POSTALCODE_INVALID                                  = 323 // The post code is not valid
	CITY_INVALID                                        = 324 // The city is not valid
	VERIFICATION_TYPE_ID_INVALID                        = 325 // The verification type id is not valid
	CIVIL_REGISTRATION_NUMBER_INVALID                   = 326 // The civil registration number is not valid
	RESET_PASSWORD_MAX_ATTEMPTS_EXCEEDED                = 327 // The max allowed number of attempts to reset the password has been exceeded.
	LIMIT_AMOUNT_GREATER_THAN_MAX_LIMIT                 = 328 // The limit amount is greater than the maximum permitted
	WEEKLY_LIMIT_EXCEEDS_DAILY_LIMIT_WEEK_AGG           = 329 // The weekly limit exceeds the aggregated daily limit for a week
	MONTHLY_LIMIT_EXCEEDS_DAILY_LIMIT_MONTH_AGG         = 330 // The monthly limit exceeds the aggregated daily limit for a month
	MONTHLY_LIMIT_EXCEEDS_WEEKLY_LIMIT_MONTH_AGG        = 331 // The monthly limit exceeds the aggregated weekly limit for a month
	LIMIT_AMOUNT_LESS_OR_EQUAL_TO_MIN_LIMIT             = 332 // The limit amount is less than or equal to the minimum allowed
	INVALID_LIMIT_START_DATE_PAST_DATE                  = 333 // The start date for the limit is in the past
	INVALID_LIMIT_START_DATE_GREATER_THAN_END_DATE      = 334 // The start date is after the specified end date
	INVALID_LIMIT_DURATION_ONLY_NODURATION_ALLOWED      = 335 // The limit duration is not valid.
	INVALID_LIMIT_DURATION_NODURATION_NOT_ALLOWED       = 336 // A valid duration must be entered
	INVALID_LIMIT_RECURRENT_LIMIT_CONTAINS_END_DATE     = 337 // An end date for a recurrent limit has been entered
	NO_CHANGE_IN_LIMIT_AMOUNT                           = 338 // There was no change in the amount specified in the limit
	LIMIT_NOT_POSSIBLE_AS_PER_COOLDOWN_POLICY           = 339 // The cool down policy means it is not possible to set this limit.
	SOWQ_ALREADY_SUBMITTED                              = 340 // The source of wealth questionnaire cannot be submitted more than once.
	SOWQ_INVALID                                        = 341 // The source of wealth questionnaire is invalid
	TIMEOUT_CATEGORY_ID_INVALID                         = 342 // The timeout category is invalid
	SOWQ_REQUESTED                                      = 343 // The source of wealth questionnaire has been requested
	SOWD_REQUESTED                                      = 344 // The source of wealth document has been requested
	INVALID_LIMIT_START_DATE_BLANK                      = 345 // The start date has been left blank
	SOWQ_ALREADY_REQUESTED                              = 346 // The source of wealth questionnaire has already been requested
	SOWQ_ANSWERS_NOT_SUBMITTED                          = 347 // The answers to the SOWQ have not been entered
	KYC_RECORD_NOT_ADDED                                = 348 // The KYC record was not added
	SOF_REQUESTED                                       = 349 // The source of funds has been requeste.
	BLOCK_BALANCE_NOTZERO                               = 350 // The balance has a value greater than 0
	BLOCK_OPEN_BONUSES                                  = 351 // Block open bonuses
	BLOCK_OPEN_ROUNDS                                   = 352 // Block open rounds
	BLOCK_OPEN_BETS                                     = 353 // Block open bets
	INVALID_RISKFREEBET                                 = 354 // The risk free bet is not valid
	SOWQ_NOT_REQUESTED                                  = 355 // The source of wealth questionnaire has not been requested
	ISOCODESUBDIVISION1_REQUIRED                        = 356 // The required code has not been entered
	ISOCODESUBDIVSION1_INVALID                          = 357 // The specified code is invalid
)
